import {readFileSync,writeFileSync,readdirSync,mkdirSync} from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {build} from 'esbuild';
const policy=JSON.parse(readFileSync('config/features.json','utf8'));
if(typeof policy.billingEnabled!=='boolean'||!policy.features||Object.values(policy.features).some(f=>!['public','member','paid'].includes(f.access)))throw Error('Invalid feature access configuration');
for(const id of ['plan.save','plan.export','templates.download'])if(policy.features[id]?.access==='public')throw Error(id+' requires an account');
const root=path.resolve('dist'),assets={};
const privateFiles=new Set(['data.js','operations-data.js','prep-tasks.js','plan-export-model.js']);
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.txt':'text/plain; charset=utf-8','.json':'application/json; charset=utf-8','.ttf':'font/ttf'};
function walk(dir){for(const ent of readdirSync(dir,{withFileTypes:true})){if(['server','.openai'].includes(ent.name))continue;const p=path.join(dir,ent.name);if(ent.isDirectory())walk(p);else{if(privateFiles.has(ent.name))continue;const rel='/'+path.relative(root,p).split(path.sep).join('/'),ext=path.extname(p),binary=ext==='.ttf';assets[rel]={body:readFileSync(p,binary?'base64':'utf8'),type:types[ext]||'application/octet-stream',...(binary?{encoding:'base64'}:{})}}}}
const indexFile=path.join(root,'index.html');let html=readFileSync(indexFile,'utf8');html=html.replace(/(src|href)="([^"?]+\.(?:js|css))(?:\?[^"]*)?"/g,(_,attr,file)=>attr+'="'+file+'?v='+createHash('sha256').update(readFileSync(path.join(root,file))).digest('hex').slice(0,10)+'"');writeFileSync(indexFile,html);walk(root);
const c={window:{}};vm.createContext(c);for(const f of ['navigation.js','data.js','operations-data.js','prep-tasks.js'])vm.runInContext(readFileSync('dist/'+f,'utf8'),c);
const handbook={...c.window.HANDBOOK_DATA,sources:c.window.HANDBOOK_SOURCES,tasks:c.window.PREP_TASKS,nav:c.window.PREP_NAV};
let exportCode='function exportModel(saved,options,data){const window={PREP_NAV:data.nav,PREP_TASKS:data.tasks,HANDBOOK_DATA:{pages:data.pages,templates:data.templates},HANDBOOK_SOURCES:data.sources};\n';
for(const [file,name] of [['planner.js','HackathonPlanner'],['schedule.js','PrepMath'],['scoring.js','ScoreRules'],['plan-export-model.js','PlanDocument']])exportCode+=readFileSync('dist/'+file,'utf8').replace(new RegExp('globalThis\\.'+name+'\\s*='),'const '+name+'=')+'\n';
exportCode+="return PlanDocument.build({settings:{durationHours:48,startLocal:'',deliveryMode:'online',scoringPreset:60,done:{},...saved},config:{...HackathonPlanner.defaults,...(saved.plan||{})},accountLoaded:true,generatedAt:Date.now()},options);}\n";
mkdirSync('.sites-runtime',{recursive:true});mkdirSync('dist/server',{recursive:true});
const entry="import {createWorker} from '../server/worker.mjs';\n"+exportCode+'const assets='+JSON.stringify(assets)+';const handbook='+JSON.stringify(handbook)+';export default createWorker(assets,'+JSON.stringify(c.window.PREP_TASKS.map(t=>t.id))+',handbook,exportModel);\n';
writeFileSync('.sites-runtime/worker-entry.mjs',entry);
await build({entryPoints:['.sites-runtime/worker-entry.mjs'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',target:'es2022',conditions:['workerd','worker','browser'],external:['node:*'],minify:true,legalComments:'eof',logLevel:'warning'});
console.log('Built authenticated Worker: '+Object.keys(assets).length+' public/guarded assets, '+handbook.tasks.length+' task IDs.');
